"""genesis — V1 schema, append-only triggers, severity_policies seed.

Revision ID: af138edd4b57
Revises:
Create Date: 2026-04-27 16:56:57.039211

This migration creates the V1 schema described in docs/schema.md in full —
nine tables, two PG ENUM types, thirteen explicit indexes, every FK action
declared (CASCADE / RESTRICT / NO ACTION / SET NULL / no FK).

It also performs three things autogenerate does NOT produce:

  1. Append-only triggers on audit_events and purge_audit per
     DECISIONS.md#012 + #014. A single shared plpgsql function
     (outrider_audit_append_only_guard) raises on UPDATE or DELETE; it is
     applied to BOTH tables. The trigger is absolute: there is no
     privileged-role bypass per #014. Created using DROP IF EXISTS +
     CREATE rather than CREATE IF NOT EXISTS — PostgreSQL's
     CREATE TRIGGER syntax does not support IF NOT EXISTS.

  2. Severity policies seed row for version "1.0.0" per the schema-layer
     spec. Without this row, the RESTRICT FK from findings.policy_version
     would block every finding insert against a fresh DB. The policy
     JSON itself is a placeholder ({}) at this stage; policy/severity.py
     (when written) is the canonical source of the actual mapping.

  3. (Implicit) ENUM type creation rides on column declarations. The two
     metadata-scoped ENUMs (review_status_enum, anomaly_status_enum) are
     created when their respective tables are created via inline
     create_type=True default behavior, and dropped with the tables on
     downgrade.

See:
  - DECISIONS.md#001-single-postgres-driver-psycopg3 (driver choice)
  - DECISIONS.md#012-data-retention-ttls-configurable-purge-on-installationdeleted
    (retention shape)
  - DECISIONS.md#014-audit-events-are-metadata-only-content-purge-targets-reviews-and-findings
    (audit append-only contract)
  - DECISIONS.md#016-llm-exchanges-stored-locally-under-retention-logs-stay-metadata-only
    (LLM content storage)
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "af138edd4b57"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # --- Hand-edited: PG ENUM types created explicitly --------------------
    # The ORM declares both ENUMs at MetaData scope (per docs/schema.md
    # "Two distinct PG ENUM types"), which means create_table does NOT
    # auto-emit CREATE TYPE for them. autogenerate renders them inline as
    # postgresql.ENUM(..., metadata=sa.MetaData()), but with metadata-
    # scoped ENUMs we have to issue CREATE TYPE before the first
    # create_table that uses each. The inline ENUMs in the create_table
    # calls below carry create_type=False so they only reference the type
    # by name, leaving lifecycle to the explicit DDL here.
    op.execute(
        """
        CREATE TYPE review_status_enum AS ENUM (
            'running',
            'awaiting_approval',
            'awaiting_approval_expired',
            'completed',
            'failed',
            'skipped'
        );
        """
    )
    op.execute(
        """
        CREATE TYPE anomaly_status_enum AS ENUM (
            'open',
            'acknowledged',
            'resolved'
        );
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column(
            "event_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("review_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("phase_key", sa.Text(), nullable=True),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False
        ),
        sa.Column("sequence_number", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("is_eval", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("review_id", "sequence_number", name="uq_audit_review_sequence"),
    )
    op.create_index(
        "ix_audit_events_review_phase_key", "audit_events", ["review_id", "phase_key"], unique=False
    )
    op.create_index(
        "ix_audit_events_review_timestamp", "audit_events", ["review_id", "timestamp"], unique=False
    )
    op.create_table(
        "installations",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("app_slug", sa.Text(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("account_login", sa.Text(), nullable=False),
        sa.Column("account_type", sa.Text(), nullable=False),
        sa.Column(
            "permissions_at_install", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("tombstoned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purge_after_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("installation_id"),
    )
    op.create_index(
        "ix_installations_tombstoned_at", "installations", ["tombstoned_at"], unique=False
    )
    op.create_table(
        "purge_audit",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("target_table", sa.Text(), nullable=False),
        sa.Column("rows_affected", sa.Integer(), nullable=False),
        sa.Column("purge_role", sa.Text(), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False
        ),
        sa.CheckConstraint("rows_affected >= 0", name="ck_purge_audit_rows_affected_nonneg"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_purge_audit_installation_timestamp",
        "purge_audit",
        ["installation_id", "timestamp"],
        unique=False,
    )
    op.create_table(
        "severity_policies",
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_table(
        "installation_repositories",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("repo_id", sa.BigInteger(), nullable=False),
        sa.Column("repo_full_name", sa.Text(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["installation_id"], ["installations.installation_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("installation_id", "repo_id", name="uq_installation_repo"),
    )
    op.create_table(
        "llm_call_content",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("completion", sa.Text(), nullable=False),
        sa.Column("is_eval", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("retention_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["audit_events.event_id"], ondelete="NO ACTION"),
        sa.ForeignKeyConstraint(
            ["installation_id"], ["installations.installation_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "ix_llm_call_content_installation_id", "llm_call_content", ["installation_id"], unique=False
    )
    op.create_index(
        "ix_llm_call_content_retention_expires_at",
        "llm_call_content",
        ["retention_expires_at"],
        unique=False,
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("repo_id", sa.BigInteger(), nullable=False),
        sa.Column("pr_number", sa.Integer(), nullable=False),
        sa.Column("head_sha", sa.Text(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "running",
                "awaiting_approval",
                "awaiting_approval_expired",
                "completed",
                "failed",
                "skipped",
                name="review_status_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("hitl_request", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("hitl_decision", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("files_examined", sa.Integer(), nullable=False),
        sa.Column("files_traced_beyond_diff", sa.Integer(), nullable=False),
        sa.Column("llm_calls_made", sa.Integer(), nullable=False),
        sa.Column("total_input_tokens", sa.Integer(), nullable=False),
        sa.Column("total_output_tokens", sa.Integer(), nullable=False),
        sa.Column("total_cost_usd", sa.Numeric(), nullable=False),
        sa.Column("wall_clock_seconds", sa.Numeric(), nullable=False),
        sa.Column("is_eval", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retention_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("files_examined >= 0", name="ck_reviews_files_examined_nonneg"),
        sa.CheckConstraint(
            "files_traced_beyond_diff >= 0", name="ck_reviews_files_traced_beyond_diff_nonneg"
        ),
        sa.CheckConstraint("llm_calls_made >= 0", name="ck_reviews_llm_calls_made_nonneg"),
        sa.CheckConstraint("total_cost_usd >= 0", name="ck_reviews_total_cost_usd_nonneg"),
        sa.CheckConstraint("total_input_tokens >= 0", name="ck_reviews_total_input_tokens_nonneg"),
        sa.CheckConstraint(
            "total_output_tokens >= 0", name="ck_reviews_total_output_tokens_nonneg"
        ),
        sa.CheckConstraint("wall_clock_seconds >= 0", name="ck_reviews_wall_clock_seconds_nonneg"),
        sa.ForeignKeyConstraint(
            ["installation_id"], ["installations.installation_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repo_id", "pr_number", "head_sha", name="uq_review_natural_key"),
    )
    op.create_index(
        "ix_reviews_active_status",
        "reviews",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status IN ('running', 'awaiting_approval')"),
    )
    op.create_index("ix_reviews_installation_id", "reviews", ["installation_id"], unique=False)
    op.create_index(
        "ix_reviews_retention_expires_at", "reviews", ["retention_expires_at"], unique=False
    )
    op.create_table(
        "anomalies",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("review_id", sa.Uuid(), nullable=True),
        sa.Column("rule_name", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "open", "acknowledged", "resolved", name="anomaly_status_enum", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("is_eval", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_anomalies_severity_created_at",
        "anomalies",
        ["severity", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "findings",
        sa.Column(
            "finding_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("review_id", sa.Uuid(), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("policy_version", sa.Text(), nullable=False),
        sa.Column("finding_type", sa.Text(), nullable=False),
        sa.Column("dimension", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("evidence_tier", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("line_start", sa.Integer(), nullable=False),
        sa.Column("line_end", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("suggested_fix", sa.Text(), nullable=True),
        sa.Column("query_match_id", sa.Text(), nullable=True),
        sa.Column("trace_path", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("original_severity", sa.Text(), nullable=True),
        sa.Column("override_reason", sa.Text(), nullable=True),
        sa.Column("overrider_id", sa.Uuid(), nullable=True),
        sa.Column("publish_destination", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("is_eval", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("retention_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("line_end >= line_start", name="ck_findings_line_end_gte_line_start"),
        sa.CheckConstraint("line_start >= 1", name="ck_findings_line_start_gte_1"),
        sa.ForeignKeyConstraint(
            ["installation_id"], ["installations.installation_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["policy_version"], ["severity_policies.version"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("finding_id"),
    )
    op.create_index("ix_findings_content_hash", "findings", ["content_hash"], unique=False)
    op.create_index("ix_findings_installation_id", "findings", ["installation_id"], unique=False)
    op.create_index(
        "ix_findings_retention_expires_at", "findings", ["retention_expires_at"], unique=False
    )
    # ### end Alembic commands ###

    # --- Hand-edited additions -------------------------------------------
    # Append-only trigger guard (shared function, applied to both tables).
    # Per DECISIONS.md#014: the trigger is absolute, with no privileged-role
    # bypass. Per docs/schema.md "Append-only enforcement on audit_events
    # AND purge_audit": #012 extends the same rule to purge_audit so the
    # forensic trail of which content rows were purged on which
    # installation.deleted event survives untouched.
    #
    # PostgreSQL CREATE TRIGGER does not support IF NOT EXISTS, so the
    # idempotent pattern is DROP TRIGGER IF EXISTS followed by CREATE
    # TRIGGER. CREATE OR REPLACE TRIGGER exists in PG 14+ but the
    # drop-then-create idiom is more portable across pre-prod / prod parity.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION outrider_audit_append_only_guard()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION
                'append-only table %: % not permitted',
                TG_TABLE_NAME, TG_OP;
        END;
        $$;
        """
    )
    op.execute(
        """
        DROP TRIGGER IF EXISTS trg_audit_events_append_only ON audit_events;
        CREATE TRIGGER trg_audit_events_append_only
            BEFORE UPDATE OR DELETE ON audit_events
            FOR EACH ROW
            EXECUTE FUNCTION outrider_audit_append_only_guard();
        """
    )
    op.execute(
        """
        DROP TRIGGER IF EXISTS trg_purge_audit_append_only ON purge_audit;
        CREATE TRIGGER trg_purge_audit_append_only
            BEFORE UPDATE OR DELETE ON purge_audit
            FOR EACH ROW
            EXECUTE FUNCTION outrider_audit_append_only_guard();
        """
    )

    # Severity policies seed row — non-negotiable for FK validity per the
    # schema-layer spec. The policy JSON is a placeholder; the actual
    # mapping is owned by policy/severity.py (when written), which can
    # update v1.0.0 in place or seed a v1.0.1 with the canonical mapping.
    # Without this row, any findings insert FK-fails on a fresh DB.
    op.execute(
        """
        INSERT INTO severity_policies (version, policy)
        VALUES ('1.0.0', '{}'::jsonb);
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # --- Hand-edited additions (run BEFORE table drops) ------------------
    # Drop triggers explicitly so the function can be dropped safely below.
    # PostgreSQL drops table-owned triggers automatically when the table
    # drops, but doing it here keeps downgrade behavior independent of
    # ordering and idempotent on partial re-runs.
    op.execute("DROP TRIGGER IF EXISTS trg_audit_events_append_only ON audit_events;")
    op.execute("DROP TRIGGER IF EXISTS trg_purge_audit_append_only ON purge_audit;")
    op.execute("DROP FUNCTION IF EXISTS outrider_audit_append_only_guard();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_findings_retention_expires_at", table_name="findings")
    op.drop_index("ix_findings_installation_id", table_name="findings")
    op.drop_index("ix_findings_content_hash", table_name="findings")
    op.drop_table("findings")
    op.drop_index("ix_anomalies_severity_created_at", table_name="anomalies")
    op.drop_table("anomalies")
    op.drop_index("ix_reviews_retention_expires_at", table_name="reviews")
    op.drop_index("ix_reviews_installation_id", table_name="reviews")
    op.drop_index(
        "ix_reviews_active_status",
        table_name="reviews",
        postgresql_where=sa.text("status IN ('running', 'awaiting_approval')"),
    )
    op.drop_table("reviews")
    op.drop_index("ix_llm_call_content_retention_expires_at", table_name="llm_call_content")
    op.drop_index("ix_llm_call_content_installation_id", table_name="llm_call_content")
    op.drop_table("llm_call_content")
    op.drop_table("installation_repositories")
    op.drop_table("severity_policies")
    op.drop_index("ix_purge_audit_installation_timestamp", table_name="purge_audit")
    op.drop_table("purge_audit")
    op.drop_index("ix_installations_tombstoned_at", table_name="installations")
    op.drop_table("installations")
    op.drop_index("ix_audit_events_review_timestamp", table_name="audit_events")
    op.drop_index("ix_audit_events_review_phase_key", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###

    # --- Hand-edited: DROP TYPE for the metadata-scoped ENUMs -------------
    # Mirrors the explicit CREATE TYPE in upgrade(). The inline ENUMs in
    # column declarations carry create_type=False so they don't try to
    # drop the type via the column-level DDL; lifecycle stays here.
    op.execute("DROP TYPE IF EXISTS anomaly_status_enum;")
    op.execute("DROP TYPE IF EXISTS review_status_enum;")
