# Skip-classification helpers per
# specs/2026-04-30-ast-facts-module.md Internal contracts.
"""Pure-Python skip-classification logic. No tree-sitter dependency.

Module-level exports:

  * `MAX_PARSE_BYTES: int = 1_048_576` — V1's DoS guard against the
    100 MB-file case. Per Internal contracts, the size check runs
    BEFORE UTF-8 decode and any other per-file work.

  * `EXCLUSION_RULES: tuple[ExclusionRule, ...]` — the ordered
    11-rule tuple. `should_skip` iterates in declared order and
    returns the first match's `reason`; the order IS the precedence
    order per Internal contracts.

  * `should_skip(file_path, source) -> SkipReason | None` — the
    classification function called by `parse_python` before any
    parser/decode work.

Imports `SkipReason` and `ExclusionRule` from `models.py` (the single
source of truth for typed shapes per project convention).
"""

from __future__ import annotations

from pathlib import PurePosixPath
from typing import Final, cast

from outrider.ast_facts.models import ExclusionRule, SkipReason

# ---------------------------------------------------------------------------
# Public constants
# ---------------------------------------------------------------------------

MAX_PARSE_BYTES: int = 1_048_576  # 1 MiB; V1 DoS guard

# Ordered tuple per Internal contracts. Precedence is by index:
# size -> path_prefix (vendored) -> filename_suffix (generated) ->
# filename_suffix (minified) -> banner (generated by content).
_VENDORED = SkipReason.VENDORED
_GEN_FN = SkipReason.GENERATED_FILENAME
_PFX = "path_prefix"
_SFX = "filename_suffix"

EXCLUSION_RULES: tuple[ExclusionRule, ...] = (
    ExclusionRule(reason=SkipReason.OVERSIZED, kind="size", pattern=MAX_PARSE_BYTES),
    ExclusionRule(reason=_VENDORED, kind=_PFX, pattern="vendor/"),
    ExclusionRule(reason=_VENDORED, kind=_PFX, pattern="node_modules/"),
    ExclusionRule(reason=_VENDORED, kind=_PFX, pattern="third_party/"),
    ExclusionRule(reason=_VENDORED, kind=_PFX, pattern=".venv/"),
    ExclusionRule(reason=_VENDORED, kind=_PFX, pattern="venv/"),
    ExclusionRule(reason=_GEN_FN, kind=_SFX, pattern="_pb2.py"),
    ExclusionRule(reason=_GEN_FN, kind=_SFX, pattern="_pb2_grpc.py"),
    ExclusionRule(reason=_GEN_FN, kind=_SFX, pattern=".pyi"),
    ExclusionRule(reason=SkipReason.MINIFIED, kind=_SFX, pattern=".min.py"),
    ExclusionRule(reason=SkipReason.GENERATED_BANNER, kind="banner", pattern=b"DO NOT EDIT"),
)

# Banner check inspects only the first N bytes of source to keep the
# check O(1) regardless of file size; size-check runs before this so
# oversized files never reach the banner check.
_BANNER_PREFIX_BYTES: Final[int] = 200


# ---------------------------------------------------------------------------
# should_skip
# ---------------------------------------------------------------------------


def should_skip(file_path: str, source: bytes) -> SkipReason | None:
    """Classify a file against `EXCLUSION_RULES` in declared order.

    Returns the first matched rule's `reason`, or `None` if no rule
    matches. The ordering is the precedence order per Internal
    contracts: size first (cheapest, no source inspection beyond
    `len(source)`), then path-pattern, then filename-suffix, then
    content-pattern (raw-byte check on first 200 bytes — no UTF-8
    decode, so this stays cheap on non-UTF-8 source).
    """
    # Defensive contract check: `file_path` MUST be POSIX repo-relative per
    # trust-boundary #5 (`coordinates/` validated and normalized it before
    # it reached us). The path_prefix exclusions below match against
    # literal POSIX prefixes (`vendor/`, `node_modules/`, ...) via
    # `str.startswith` — an absolute path or backslash path would silently
    # bypass the exclusions, so fail loudly instead. Test fixtures and
    # REPL callers that violate the contract get an actionable error
    # rather than a silent miss.
    if file_path.startswith("/") or "\\" in file_path:
        msg = (
            f"file_path must be POSIX repo-relative per trust-boundary #5; "
            f"got {file_path!r}. `coordinates/` is responsible for normalization "
            f"before paths reach `ast_facts/`."
        )
        raise ValueError(msg)
    # PurePosixPath here is used only to extract the trailing filename
    # component for suffix matching; the prefix check above guards the
    # `path_prefix` rule's literal-startswith semantics.
    relative = PurePosixPath(file_path)
    name = relative.name

    # Pydantic's cross-field validator on ExclusionRule already enforces
    # the kind/pattern type pairing at construction time, so the casts
    # below are typing-only narrowing for mypy/ruff.
    for rule in EXCLUSION_RULES:
        # `>` per canonical §5.5 wording ("source byte length exceeding
        # `MAX_PARSE_BYTES`") and the approved ast_facts/ spec
        # (`len(source) > MAX_PARSE_BYTES`). A file of exactly
        # MAX_PARSE_BYTES bytes (1 MiB) passes through. If the boundary
        # case ever needs OVERSIZED treatment, that's a canonical
        # amendment routed via DECISIONS.md, not a silent code change.
        if rule.kind == "size" and len(source) > cast("int", rule.pattern):
            return rule.reason
        if rule.kind == "path_prefix" and file_path.startswith(cast("str", rule.pattern)):
            return rule.reason
        if rule.kind == "filename_suffix" and name.endswith(cast("str", rule.pattern)):
            return rule.reason
        # Case-insensitive raw-byte check per Internal contracts.
        # `bytes.upper()` works on ASCII subsequences without UTF-8
        # decode, preserving size-and-pattern-before-decode ordering.
        #
        # Known residual: UTF-16/UTF-32-encoded source files with a
        # generated-banner prefix (e.g., `\xff\xfe` BOM + UTF-16-LE
        # encoding) won't match because `D\x00O\x00 \x00...` doesn't
        # contain the contiguous bytes `b"DO NOT EDIT"`. Such files
        # then fail UTF-8 decode at step (4) and route to
        # `parser_outcome="failed"` rather than `"skipped"`. Acceptable
        # for V1: UTF-16 Python source is exotic, and the file still
        # surfaces in audit (as failed instead of skipped). If real PRs
        # ever hit this, V1.5 could detect a BOM at offset 0 and run
        # the banner check after a bounded UTF-16 decode of the prefix.
        if (
            rule.kind == "banner"
            and cast("bytes", rule.pattern) in source[:_BANNER_PREFIX_BYTES].upper()
        ):
            return rule.reason

    return None
