/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive Pull Request Webhook
         * @description Receive a GitHub pull_request webhook, seed a review, dispatch the graph.
         */
        post: operations["receive_pull_request_webhook_webhooks_github_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{review_id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide
         * @description Accept a HITL approval submission for `review_id`.
         *
         *     Flow (M12 step-order is load-bearing):
         *       1. Auth (via `require_admin_api_key` Depends). 401 on failure.
         *       2. State preflight via `ReviewStatusReader.fetch_for_decide`.
         *          409 if: hitl_request is None / status not in the HITL set /
         *          hitl_decision already landed.
         *       3. Mismatch check: payload `finding_id` set must equal the
         *          gated set on `hitl_request.findings_requiring_approval`.
         *          422 with `{"missing": [...], "extras": [...]}` on mismatch.
         *       4. Construct typed `HITLDecision` server-side (server-set
         *          `reviewer_id`, server-derived `original_severity` from the
         *          preflight map for SEVERITY_OVERRIDE outcomes, server-set
         *          `decided_at=datetime.now(UTC)`).
         *       5. Enqueue `_run_resume_under_failure_wrapper` via FastAPI
         *          `BackgroundTasks`; return 202 immediately.
         */
        post: operations["decide_reviews__review_id__decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reviews
         * @description The review queue. Excludes `is_eval=True` rows unless
         *     `include_eval=true` (eval-isolation default per `docs/testing.md`).
         */
        get: operations["list_reviews_api_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review
         * @description One review's detail + audit-stream-computed metrics. 404 if absent.
         *
         *     A direct fetch by id is not `is_eval`-filtered — the list endpoint is the
         *     eval-isolation surface; holding the id is sufficient to view it.
         */
        get: operations["get_review_api_reviews__review_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Findings
         * @description A review's findings, assembled from the permanent audit record.
         *
         *     404 if the review doesn't exist. Surviving `findings`-table rows render as
         *     full findings; a `FindingEvent` whose `findings` row was purged under
         *     retention renders as a `content_redacted=True` stub from `FindingEvent`
         *     metadata (DECISIONS.md#014 point 3 — the audit trail outlives the content).
         *     Each finding's publish lifecycle is joined from the audit stream:
         *     `publish_destination` (`PublishRoutingEvent`) and `eligibility` /
         *     `eligibility_reason` (`PublishEligibilityEvent`) — separate per
         *     DECISIONS.md#023, so a routed finding can still show `withheld`. None of
         *     these are read from the (V1-null) `findings.publish_destination` column.
         */
        get: operations["list_findings_api_reviews__review_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Replay Verdict
         * @description Replay-equivalence verdict — wraps `audit/replay.py::AuditReplayer`.
         *
         *     404 if the review has no audit-event rows (`ReplayReviewNotFoundError`).
         *     Single-snapshot: `reconstruct` (one REPEATABLE READ snapshot) gives mode +
         *     counts, then `assert_equivalent` verifies THAT SAME reconstruction — so the
         *     verdict can't mix counts from one snapshot with pass/fail from another (the
         *     bug if we re-ran `assert_replay_equivalent`, which reconstructs again). Both
         *     read-only (no mutation). A `ReplayEquivalenceError` from either step yields
         *     `replay_equivalent=False` carrying the failing check's message, NOT a 500 —
         *     the verdict IS the product. (A corrupt payload that won't even deserialize
         *     surfaces as the underlying `ValidationError` → 500, the genuine-corruption
         *     case.) `phases` is intentionally not exposed (FUP-125).
         */
        get: operations["get_replay_verdict_api_reviews__review_id__replay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description **Liveness only**, not readiness.
         *
         *     Returns 200 once the lifespan reaches its `yield` (i.e., the
         *     process booted and dependency CONSTRUCTORS ran without raising).
         *     It does NOT probe DB connectivity, Anthropic reachability, or
         *     GitHub-API health — the lifespan's construction may have built an
         *     engine pointed at an unreachable Postgres host and this endpoint
         *     would still return 200.
         *
         *     Useful as a "did uvicorn boot" smoke test behind smee.io /
         *     cloudflared / nginx. NOT a substitute for an actual readiness
         *     probe; layer that on top if you need it.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * FindingSeverity
         * @description Severity tier assigned by SEVERITY_POLICY, never by the model.
         * @enum {string}
         */
        FindingSeverity: "critical" | "high" | "medium" | "low" | "info";
        /**
         * FindingView
         * @description One finding, assembled from the permanent audit record + content.
         *
         *     Metadata (type/severity/file/line/dimension/tier/proof) comes from the
         *     `FindingEvent` audit row (permanent). Content (`title`/`description`/
         *     `evidence`/`suggested_fix`) comes from the `findings` table — present
         *     within the retention window, `None` with `content_redacted=True` once the
         *     row is purged but the `FindingEvent` survives (DECISIONS.md#014 point 3:
         *     "render a dangling finding_id as content redacted per retention policy").
         *
         *     Lifecycle fields joined from the audit stream (per DECISIONS.md#023's
         *     routing≠eligibility split): `publish_destination` from `PublishRoutingEvent`
         *     (where coordinates classified it); `eligibility` / `eligibility_reason`
         *     from `PublishEligibilityEvent` (whether it actually materialized). A
         *     high/critical finding pre-HITL shows `inline_comment` + `withheld` +
         *     `hitl_required_node_absent` — routed but not posted. All three are `None`
         *     until publish runs.
         *
         *     HITL override-provenance (original→override severity / outcome / reason)
         *     is a separate follow-up — FUP-128.
         */
        FindingView: {
            /**
             * Finding Id
             * Format: uuid
             */
            finding_id: string;
            /** Finding Type */
            finding_type: string;
            /** Dimension */
            dimension: string;
            /** Severity */
            severity: string;
            /** Evidence Tier */
            evidence_tier: string;
            /** File Path */
            file_path: string;
            /** Line Start */
            line_start: number;
            /** Line End */
            line_end: number;
            /** Content Redacted */
            content_redacted: boolean;
            /** Title */
            title: string | null;
            /** Description */
            description: string | null;
            /** Evidence */
            evidence: string | null;
            /** Suggested Fix */
            suggested_fix: string | null;
            /** Query Match Id */
            query_match_id: string | null;
            /** Trace Path */
            trace_path: string[] | null;
            /** Publish Destination */
            publish_destination: string | null;
            /** Eligibility */
            eligibility: string | null;
            /** Eligibility Reason */
            eligibility_reason: string | null;
            /** Redaction Sweep At */
            redaction_sweep_at: string | null;
        };
        /** FindingsResponse */
        FindingsResponse: {
            /**
             * Review Id
             * Format: uuid
             */
            review_id: string;
            /** Findings */
            findings: components["schemas"]["FindingView"][];
        };
        /**
         * HITLDecisionPayload
         * @description Body shape for `POST /reviews/{review_id}/decide`.
         *
         *     `decisions` is a non-empty tuple bounded at 256 entries (matches
         *     `HITLRequest.findings_requiring_approval` producer-side cap);
         *     `annotation` is optional forensic prose, capped at 2000 chars
         *     matching `HITLDecisionEvent.annotation`.
         */
        HITLDecisionPayload: {
            /** Decisions */
            decisions: components["schemas"]["PerFindingDecisionPayload"][];
            /** Annotation */
            annotation?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PerFindingDecisionPayload
         * @description Reviewer-submitted decision shape.
         *
         *     Distinct from `PerFindingDecision`: `original_severity` is NOT
         *     accepted here (the endpoint derives it server-side from the
         *     persisted `FindingEvent.severity` via `ReviewDecidePreflight`)
         *     AND `reviewer_id` is NOT in this payload (set server-side from
         *     auth context to the literal `admin` under V1 ADMIN_API_KEY
         *     scope).
         */
        PerFindingDecisionPayload: {
            /**
             * Finding Id
             * Format: uuid
             */
            finding_id: string;
            outcome: components["schemas"]["PerFindingOutcome"];
            /** Reason */
            reason: string;
            override_severity?: components["schemas"]["FindingSeverity"] | null;
        };
        /**
         * PerFindingOutcome
         * @description Per-finding HITL decision outcomes per spec §7.4.
         * @enum {string}
         */
        PerFindingOutcome: "approve" | "reject" | "suppress" | "severity_override";
        /**
         * ReplayVerdict
         * @description Replay-equivalence verdict for one review — a thin wrapper over
         *     `audit/replay.py::AuditReplayer`.
         *
         *     Deliberately does NOT expose `reconstruct()`'s `phases` grouping (FUP-125:
         *     trustworthy only after `assert_replay_equivalent`) — only the mode, the
         *     counts, and the pass/fail verdict. `mode`/`event_count`/`finding_count`/
         *     `orphan_finding_count` are `None` only when `reconstruct` itself raised
         *     (corrupt row/payload/is_eval drift). `reason` carries the failing-check
         *     message when not equivalent — metadata only (ids / hashes / counts /
         *     enum values), never finding content (per the replay verifier's design).
         */
        ReplayVerdict: {
            /**
             * Review Id
             * Format: uuid
             */
            review_id: string;
            /** Replay Equivalent */
            replay_equivalent: boolean;
            /** Mode */
            mode: string | null;
            /** Event Count */
            event_count: number | null;
            /** Finding Count */
            finding_count: number | null;
            /** Orphan Finding Count */
            orphan_finding_count: number | null;
            /** Reason */
            reason: string | null;
        };
        /** ReviewDetail */
        ReviewDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Installation Id */
            installation_id: number;
            /** Repo Id */
            repo_id: number;
            /** Pr Number */
            pr_number: number;
            /** Head Sha */
            head_sha: string;
            /** Status */
            status: string;
            /** Is Eval */
            is_eval: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Expires At */
            expires_at: string | null;
            metrics: components["schemas"]["ReviewMetricsView"];
            /** Policy Version */
            policy_version: string | null;
        };
        /** ReviewListItem */
        ReviewListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Installation Id */
            installation_id: number;
            /** Repo Id */
            repo_id: number;
            /** Pr Number */
            pr_number: number;
            /** Head Sha */
            head_sha: string;
            /** Status */
            status: string;
            /** Is Eval */
            is_eval: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Completed At */
            completed_at: string | null;
            metrics: components["schemas"]["ReviewMetricsView"];
        };
        /** ReviewListResponse */
        ReviewListResponse: {
            /** Reviews */
            reviews: components["schemas"]["ReviewListItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * ReviewMetricsView
         * @description Audit-stream-computed metrics for one review (see module docstring).
         *
         *     File/wall-clock fields are `None` when the review has no
         *     `SynthesizeCompletedEvent` yet — render pending, never zero.
         */
        ReviewMetricsView: {
            /** Llm Calls Made */
            llm_calls_made: number;
            /** Total Input Tokens */
            total_input_tokens: number;
            /** Total Output Tokens */
            total_output_tokens: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Files Examined */
            files_examined: number | null;
            /** Files Traced Beyond Diff */
            files_traced_beyond_diff: number | null;
            /** Wall Clock Seconds */
            wall_clock_seconds: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * _DecideResponse
         * @description 202 Accepted body.
         */
        _DecideResponse: {
            /** Review Id */
            review_id: string;
            /** Status */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    receive_pull_request_webhook_webhooks_github_post: {
        parameters: {
            query?: never;
            header?: {
                "x-hub-signature-256"?: string | null;
                "x-github-event"?: string | null;
                "x-github-delivery"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_reviews__review_id__decide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HITLDecisionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_DecideResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reviews_api_reviews_get: {
        parameters: {
            query?: {
                status?: ("running" | "awaiting_approval" | "awaiting_approval_expired" | "completed" | "failed" | "skipped") | null;
                repo_id?: number | null;
                include_eval?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_api_reviews__review_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_api_reviews__review_id__findings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_replay_verdict_api_reviews__review_id__replay_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayVerdict"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
